<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ros_awsiot_agent</name>
  <version>0.0.0</version>
  <description>This package provides bridge functionalities between ROS2 and AWS IoT</description>

  <maintainer email="tadashi.imokawa@whill.inc">Tadashi Imokawa</maintainer>
  <license>MIT</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>rosidl_default_runtime</exec_depend>
  <exec_depend>rosbridge_library</exec_depend>
  <exec_depend>python3-awsiotclient-pip</exec_depend>

  <test_depend>python3-pytest</test_depend>
  <test_depend>ros_testing</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>

</package>
